### ISSUE TITLE
Temporal BEV feature align

### ISSUE THREAD

**Issue by QixingJiang** [Sense-X/HoP#1]
Dear author,
Hello,
Great Works! When will the code be released?
Before the code is released, I am wondering how do you align the BEV features at different timestamps in your short-term/long-term temporal decoder. Can you give some clues?
Thank you for your time.

**Comment by CaraJ7** [comment]
Hi @QixingJiang, thanks for your interest in our work.

We align all the BEV features to the current timestamp $t$, as illustrated in the Section 3.1 in our paper.

**Comment by QixingJiang** [comment]
Thank you for your reply :)
I have tracked your code releasing today and found the corresponding code at 
https://github.com/Sense-X/HoP/blob/bffcb2f02d568e9339cb827d9a5eedd961ab5323/mmdet3d_plugin/hop/detectors/hop_bevdet.py#L67
Now I get how it works!
