### ISSUE TITLE
Pretrained weights for NuScenes detection

### ISSUE THREAD

**Issue by eldar** [Sense-X/HoP#2]
Hi all, congrats on your amazing results. Is it possible to share pretrained weights on NuScenes? I would like to try the model without training it from scratch.

**Comment by CaraJ7** [comment]
Hi, you can download the checkpoint of HoP_BEVDet with [this link](https://github.com/Sense-X/HoP/releases/download/Release/HoP_BEVDet_ep24_ema.pth). Please refer to the [config file](https://github.com/Sense-X/HoP/blob/main/configs/hop_bevdet/hop_bevdet4d-r50-depth.py) for detailed information of the checkpoint.
