### ISSUE TITLE
How to get the ground truth of history frames?

### ISSUE THREAD

**Issue by jinhuan-hit** [Sense-X/HoP#3]
Good job! I am wondering how do you get the ground truth of history frames for nuscenes dataset?

**Comment by TempleX98** [comment]
We transform history 3D ground truth to current coordinate system [here](https://github.com/Sense-X/HoP/blob/bffcb2f02d568e9339cb827d9a5eedd961ab5323/mmdet3d/datasets/pipelines/loading.py#L1196)

**Comment by jinhuan-hit** [comment]
Got it! Tnanks for your quick reply.
